# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7d8fdac85a382f73ab18694cf28af4fd42718f26127c0537e636fbfe64e020650445f8168976fd2ac3755ac4897228d1c83585bbbf76bb96a3439461652dee0

test:
  secret_key_base: cc425ee5781a509991687752aecf43bc77da12d2704c7ebb406e32aa31ad75a184fd4532dc837f6711c263f39e8f64d503e1fc00c116c45e8ea63e3431382790

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
